language: julia

os:
    - linux
    - osx
    
julia:
    - 0.7
    - nightly

matrix:
  fast_finish: true
  allow_failures:
    - julia: nightly

notifications:
  email: false

after_success:
    - julia -e 'cd(Pkg.dir("MLKernels")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
