name = "MLKernels"
uuid = "48eadcf2-8ff1-11e8-289d-f103432a0bb3"
authors = ["gdkrmr <gdkrmr@users.noreply.github.com>"]
version = "0.2.9999"

[deps]
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
